services:
  db:
    image: postgres:latest  # Use the official PostgreSQL image
    ports:
      - "5431:5432"  # Map the PostgreSQL port
    environment:
      - POSTGRES_USER=postgres  # Set the username for the database
      - POSTGRES_PASSWORD=postgres  # Set the password for the database
      - POSTGRES_DB=postgres  # Set the database name
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist database data

  redis:
    image: redis:latest  # Use the official Redis image
    ports:
      - "6878:6379"  # Map the Redis port
    volumes:
      - redis-data:/data  # Persist Redis data

volumes:
  db-data:  # Define the volume for PostgreSQL data
  redis-data:  # Define the volume for Redis data
